### ISSUE TITLE
Incluir package.json

### ISSUE THREAD

**Issue by andcastillo** [gelkio/testCountry#1]
No hay package.json donde se especifiquen las librerías que se usan en el proyecto. Incluya uno de forma que antes de correr el proyecto se puedan instalar las dependencias usando

```
npm install
```

**Comment by gelkio** [comment]
Se incluyó el archivo package.json para permitir todo el manejo de la aplicación usando npm.

**Comment by andcastillo** [comment]
Gracias. Mucho mejor.
Closed via: b4c16320ec82a3e0de0596b0f8c88b64f7c5e127
